---
title: "Bank Marketing Analysis"
author: "Zixun Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Proposal

1.  Data

The data set in this project is the Bank Market Data Set from UC Irvine Machine Learning Repository. It contains the costumer persona of bank client. The feature contains as follows:

1 - age (numeric)\
2 - job : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')\
3 - marital : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)\
4 - education (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')\
5 - default: has credit in default? (categorical: 'no','yes','unknown')\
6 - housing: has housing loan? (categorical: 'no','yes','unknown')\
7 - loan: has personal loan? (categorical: 'no','yes','unknown')\
\# related with the last contact of the current campaign:\
8 - contact: contact communication type (categorical: 'cellular','telephone')\
9 - month: last contact month of year (categorical: 'jan', 'feb', 'mar', \..., 'nov', 'dec')\
10 - day_of_week: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')\
11 - duration: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.\
\# other attributes:\
12 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)\
13 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)\
14 - previous: number of contacts performed before this campaign and for this client (numeric)\
15 - poutcome: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')\
\# social and economic context attributes\
16 - emp.var.rate: employment variation rate - quarterly indicator (numeric)\
17 - cons.price.idx: consumer price index - monthly indicator (numeric)\
18 - cons.conf.idx: consumer confidence index - monthly indicator (numeric)\
19 - euribor3m: euribor 3 month rate - daily indicator (numeric)\
20 - nr.employed: number of employees - quarterly indicator (numeric)

The label of the data set is whether the customer subscribed a term deposit.

The data will be preprocessed at the beginning of the project. The categorical data will be encoded by one hot encoder. The numerical data will be normalized if it significantly different mean and standard deviation.

2.  Modeling Goal

Generate a predictive model where we get specific information of a client and identify if the client subscribed a term deposit. In real world context, this helps the banks to identify the potential client of term deposit service when they utilize the model on customer persona.

3.  Methodology

Various classification methods will be deployed in this projects including logistic regression, decision tree, and random forest. The introduction of each model are shown as follow:

3.1 Logistic regression

Logistic regression is a linear classification model where the log odd is predicted by a linear function with the features. Feature selection according to importance and conduct hypothesis test on coefficient are necessary as there might be feature which has minor effect on the labels.

3.2 Decision Tree

Decision tree will build a model where the nodes splits by calculating the cutoff with minimum the gini index, and the tree stops generating at gini index reaches 0 at each nodes. After the tree is built, we may access it to make classification predictions. Even if overfitting is likely to happen, we may address this by prune the tree.

3.3 Random Forest

Random forest is a model where the classification decision is made according to most common decision tree result in a number of random generated decision trees. This model is also likely to have overfitting. Hyperparameter tuning will be deployed to ensure there is no overfitting.

After the models are built, the optimal threshhold will be selected for each model according to context requirement such as high specificity or high sensitivity.

The evaluation of the models is not only seeking for accuracy but also interpretability. Visualization tools such as confusion matrix, ROC curve, and feature importance plot will be deployed in the project to ensure the models are understandable and reproducible. At the end of this project, the model selection will be based on not only numerical metrics such as accuracy or loss but also visualized metrics such as feature importance plot and ROC curve to ensure interpretability, acceptable model complexity, and preciseness.
