# [Decision Tree]

```{r,cache=TRUE}
library(rpart)
library(rpart.plot)

DTmod <- rpart(y ~ ., data = train_dat,cp=0,method='class')
pred <- function(model, newdata) {
  predict(model, newdata = newdata, type = "prob")[, 2]
}

rpart.plot(DTmod)
```

```{r,cache=TRUE}
plotcp(DTmod)
```


```{r,cache=TRUE}
DTmod <- rpart(y ~ ., data = train_dat,cp=0.0027,method='class')

DTpred = predict(DTmod,test_dat)[,2]
mean((DTpred>0.5)==(test_dat$y=='yes'))
```

```{r,cache=TRUE}
rpart.plot(DTmod)
```

```{r,cache=TRUE}
medabs<-function(input){
  abs(median(input))
}

shap_values <- fastshap::explain(
  DTmod, 
  X = train_dat,           
  feature_names = colnames(train_dat |> dplyr::select(-y)),
  pred_wrapper = pred, 
  nsim = 5,
  newdata = test_dat
)

library(ggplot2)
library(reshape2)
ggplot(melt(shap_values),aes(value, reorder(variable, value, FUN = medabs)))+
  geom_boxplot(outlier.size=1)
```



```{r,cache=TRUE}
library(pdp)
pdp_hit_rf = partial(DTmod,pred.var = 'InterestRateindex',prob = TRUE,type = 'classification')
g <- ggplot(pdp_hit_rf, aes(InterestRateindex, yhat)) +
  geom_line() +
  geom_rug(data = train_dat, aes(InterestRateindex), inherit.aes = FALSE, alpha = .5,
  color = "red") +
  theme_bw(16)
g+ylab('prob')
```
```{r,cache=TRUE}
library(pdp)
pdp_hit_rf = partial(DTmod,pred.var = 'confidenceIndex',prob = TRUE,type = 'classification')
g <- ggplot(pdp_hit_rf, aes(confidenceIndex, 1/(1+exp(yhat)))) +
  geom_line() +
  geom_rug(data = train_dat, aes(confidenceIndex), inherit.aes = FALSE, alpha = .5,
  color = "red") +
  theme_bw(16)
g+ylab('prob')
```

```{r,cache=TRUE}
library(pdp)
pdp_hit_rf = partial(DTmod,pred.var = 'priceIndex',prob = TRUE,type = 'classification')
g <- ggplot(pdp_hit_rf, aes(priceIndex, 1/(1+exp(yhat)))) +
  geom_line() +
  geom_rug(data = train_dat, aes(priceIndex), inherit.aes = FALSE, alpha = .5,
  color = "red") +
  theme_bw(16)
g+ylab('prob')
```



```{r,cache=TRUE}
get_rates <- function(threshold, actual, response) {
  predicted <- ifelse(response < threshold, 0, 1)
  
  TP <- sum(actual == 1 & predicted == 1)
  FP <- sum(actual == 0 & predicted == 1)
  TN <- sum(actual == 0 & predicted == 0)
  FN <- sum(actual == 1 & predicted == 0)
  
  tpr <- TP/(TP + FN)
  fpr <- FP/(TN + FP)  
  
  data.frame(threshold, tpr, fpr)
  
}


rocdf <- map_df(seq(0, 1, .01), get_rates, test_dat$y=='yes', DTpred)
rocdf <- rocdf |> 
  mutate(label = ifelse(threshold %in% seq(0, 1, .01),
                        threshold, NA))
library(ggrepel)
g <- ggplot(rocdf, aes(x = fpr, y = tpr, label = label)) +
  geom_point() +
  geom_path() +
  geom_label_repel(color = "blue", size = 2)
plotly::ggplotly(g)
```