# Reflections

In terms of the predicting models, the three models have create some meaningful result. If we select the 5 most significant variables from each model, it is obvious that there are variables being named multiple time such as outcome of previous campaign, interest rate index, price index, and age. We may conclude these variables as influential variables to predicting whether the person has term deposit. Among all the three models, logistic regression and random forest reaches best accuracy and roc curves.

In terms of interpreting the models, visualization of black box models does provide a more intuitive information helping people inspect the effect of specific feature. However, the visualization may be distorted from true relationship by lack of data or unbalance in data. This is exactly the reason why some of the visualization contradicts with the result from EDA or result from other models. Therefore, it is important for us to take a larger, and more balanced dataset in the future, so that our visualization tools may reflect the true relationship between features and target variables. Among all the models, decision tree and logistic regression achieved best interpretation as they are interpretable models.

In conclusion, we may access these models via both performance metrics and interpretability. For this dataset, I would choose logistic regression as it achieves both high accuracy and interpretability comparing to decision tree and random forest. Moreover, we would expect better performance metrics and better explainability by having a more balanced dataset.

